tap "caskroom/cask"
tap "caskroom/versions"

# Core Brew Dependencies
brew 'coreutils'
brew 'redis'
brew 'git'
brew 'siege'
brew 'rethinkdb'
brew 'hub'

# Brew Cask Dependencies
cask_args appdir: '/Applications'
cask 'dropbox'
cask 'hyperdock'
cask 'screenflow'
cask '1password'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'iterm2'
cask 'alfred'
cask 'sublime-text3'
cask 'kaleidoscope'
cask 'spotify'
cask 'cloudup'
cask 'atom'

# Mac App Store Dependencies
mas 'Day One', id: 1055511498
mas 'iA Writer', id: 775737590
