tap "caskroom/cask"

# Core Brew Dependencies
brew 'git'
brew 'hub'

# Brew Cask Dependencies
cask_args appdir: '/Applications'
cask 'dropbox'
cask 'hyperdock'
cask '1password'
cask 'firefox'
cask 'google-chrome'
cask 'alfred'
cask 'kaleidoscope'
cask 'spotify'
cask 'cloudup'
cask 'visual-studio-code'
cask 'hyper'

# Mac App Store Dependencies
mas 'Day One', id: 1055511498
